### PR TITLE
add our team section

### LINKED ISSUE #5: Our Team Section
#Tasks
* create our team section
* style this section 
* make the section Responsive

### PR DESCRIPTION
**Pull request by Heba-elLouh**
Relates #5

* Write the html code for our team section .
* add the style for the code .
* add the media style .

### CODE REVIEW

**Review by emanjaber — DISMISSED** [review]
Nice style Heba! （づ￣3￣）づ╭❤～

**Review by reemsh2000 — APPROVED** [review]

**Review by reemsh2000 — DISMISSED** [review]

**Review by emanjaber — APPROVED** [review]
Perfect Heba!

**Review by sara219 — APPROVED** [review]
well done, everything looks great 👏

**Comment by Heba-elLouh** [comment]
> well done, everything looks great 👏

thanks Sara .

**Review by suhail-radwan — APPROVED** [review]

**Pull request merged**
